name: The Stress Engine CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  audit-and-test:
    uses: open-souse/cicd-standards/.github/workflows/node-standard.yml@main
    with:
      node-version: '20'
      test-command: 'npm test'
    secrets:
      NPM_TOKEN: ${{ secrets.FORT_KNOX_AUTOMATION }}
